# Generated by Django 6.0.2 on 2026-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_ai_prompt_post_ai_style_post_use_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ai_style',
            field=models.CharField(blank=True, choices=[('auto', 'Auto Enhance (Pencerah)'), ('noir', 'Hitam Putih (Noir)'), ('sepia', 'Vintage / Sepia'), ('sketch', 'Sketsa Pensil'), ('cyber', 'Cyberpunk (Neon)'), ('hdr', 'HDR (High Dynamic Range)'), ('cartoon', 'Efek Kartun')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='use_ai',
            field=models.BooleanField(default=False),
        ),
    ]
