# Generated by Django 6.0.2 on 2026-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_alter_post_ai_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_strength',
            field=models.FloatField(default=0.35, help_text='0.1 (Mirip Asli) - 0.9 (Imajinasi Liar)'),
        ),
    ]
