# Generated by Django 6.0.2 on 2026-02-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_error_message_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enhance_face',
            field=models.BooleanField(default=True, help_text='Apply GFPGAN face restoration'),
        ),
        migrations.AddField(
            model_name='post',
            name='face_image',
            field=models.ImageField(blank=True, help_text='Reference image for Face Swap', null=True, upload_to='posts/faces/'),
        ),
    ]
