# Generated by Django 6.0.2 on 2026-02-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_enhance_face_post_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='enhance_face',
        ),
        migrations.RemoveField(
            model_name='post',
            name='face_image',
        ),
    ]
