# Generated by Django 6.0.2 on 2026-02-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_enhance_face_remove_post_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generation_type',
            field=models.CharField(choices=[('text_to_image', 'Text to Image'), ('image_to_image', 'Image + Text to Image'), ('text_to_video', 'Text to Video'), ('image_to_video', 'Image to Video')], default='text_to_image', help_text='Pilih jenis generation yang diinginkan', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='video_prompt',
            field=models.TextField(blank=True, help_text='Prompt khusus untuk gerakan/video (opsional, jika berbeda dari ai_prompt)', null=True),
        ),
    ]
